GET http://localhost:5000/api/user/getMe/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTAwNmZlNjNiNjNkNDc2YTUzNDYwZmIiLCJlbWFpbCI6InFxQHFxLnFxIiwiaWF0IjoxNjk0NjMzMzQxLCJleHAiOjE2OTQ2MzY5NDF9.VYDM8Y4fed3v-iYns2AjH7vobHOVgNjLmY5zLimVI6Q HTTP/1.1
